FROM python:3.11-slim

WORKDIR /app

# Install required system tools
RUN apt-get update && apt-get install -y \
    ffmpeg \
    tcpdump \
    curl \
    iproute2 \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
